gene:
    prodigal:
        # params: '-p meta'
        params: '-p single'
        priority: 90
        threads: 1
ncRNA:
    cmscan:
        params: ''
        priority: 50
        threads: 1
        db: '~/database/rfam/rfam.cm'
CRISPR:
    minced:
        params: ''
        priority: 50
        threads: 1
tRNA:
    aragorn:
        params: '-w'
        priority: 50
        threads: 1
# rRNA:
#     cmscan:
#         params: ''
#         priority: 50
#         threads: 1
#         db: 'rRNA.cm'
protein:
# homologous search for proteins
    diamond_uniref90:
        params: '--index-chunks 1 --query-cover 80 -k 3'
        priority: 50
        threads: 1
        db: '~/database/uniref/uniref90.dmnd'
        input: 'prodigal.faa'
        output: 'diamond_uniref90'
    diamond_uniref50:
        params: '--index-chunks 1 --query-cover 80 -k 3'
        priority: 50
        threads: 1
        db: '~/database/uniref/uniref50.dmnd'
        input: 'diamond_uniref90.faa'
        output: 'diamond_uniref50'
    # hmmscan_tigrfam:
    #     params: '−−cug_nc'
    #     priority: 60
    #     threads: 1
    #     db: '~/database/tigrfam/tigrfam.hmm'
    #     input: ''
    #     output: ''
    # hmmscan_tigrfam:
    #     params: '−−cug_ga'
    #     priority: 60
    #     threads: 1
    #     db: '~/database/tigrfam/tigrfam.hmm'
    #     input: ''
    #     output: ''

general:
    metadata: '~/database/protein.sqlite'
